particlesJS("particles-js",{
    "particles":{
      "number":{
        "value":100,
        "density":{
          "enable":true,
          "value_area":1000
        }
      },
      "color":{
        "value":"#ffffff"
      },
      "shape":{
        "type":"polygon",
        "stroke":{
          "width":0,
        },
    "polygon":{
      "nb_sides":6
    },
    "image":{
      "width":10,
      "height":10
    }
    },
      "opacity":{
      "value":0.6,
      "random":false,
      "anim":{
        "enable":true,
        "speed":1,
        "opacity_min":0.01,
        "sync":false
      }
      },
      "size":{
        "value":3,
        "random":true,
        "anim":{
          "enable":false,
          "speed":40,
          "size_min":0.1,
          "sync":false
        }
      },
      "line_linked":{
        "enable":true,
        "distance":150,
        "color":"#ffffff",
        "opacity":0.5,
        "width":1
      },
      "move":{
        "enable":true,
        "speed":-1,
        "direction":"none",
        "random":false,
        "straight":false,
        "out_mode":"out",
        "bounce":false,
        "attract":{
          "enable":false,
          "rotateX":10,
          "rotateY":10
        }
      }
    },
    "interactivity":{
      "detect_on":"canvas",
      "events":{
        "onhover":{
          "enable":false,
          "mode":"repulse"
        },
    "onclick":{
      "enable":false
    },
    "resize":true
      }
    },
    "retina_detect":true
  });